model_name_or_path: unsloth/Qwen2.5-7B
id2label_path: result/final_weight/final_lora_adapter/id2label.json
label2id_path: result/final_weight/final_lora_adapter/label2id.json
max_seq_length: 512
max_new_tokens: 12
load_in_4bit: true
dtype: none
eval_csv: sample_data/clean_data/test.csv
report_dir: result/inf_base
batch_size: 4
num_correct_samples: 5
num_wrong_samples: 5
