model_variant: base
base_model_name_or_path: distilbert-base-uncased
id2label_path: outputs/id2label.json
label2id_path: outputs/label2id.json
max_length: 64
eval_csv: sample_data/clean_data/test.csv
report_dir: outputs/inference_base
batch_size: 16
num_correct_samples: 5
num_wrong_samples: 5
